// <auto-generated />
using System;
using DataBasse.DBConnection.ReadDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBasse.Migrations
{
    [DbContext(typeof(ShortUrlReadDbContext))]
    [Migration("20250211114249_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.UrlInfo", b =>
                {
                    b.Property<string>("shortUrl")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<uint>("ClicksNumber")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("shortUrl");

                    b.ToTable("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
